/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardConnectionsRouteImport } from './routes/dashboard.connections'
import { Route as DashboardCustomersImportRouteImport } from './routes/dashboard.customers-import'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardPostingLogRouteImport } from './routes/dashboard.posting-log'
import { Route as DashboardRemovalsRouteImport } from './routes/dashboard.removals'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardStripeReadinessRouteImport } from './routes/dashboard.stripe-readiness'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ApiPostingAttemptsCsvRouteImport } from './routes/api/posting-attempts.csv'
import { Route as ApiPublicCronOutreachTickRouteImport } from './routes/api/public/cron/outreach-tick'
import { Route as ApiPublicCronPollYelpRouteImport } from './routes/api/public/cron/poll-yelp'
import { Route as ApiPublicCronPostDraftsRouteImport } from './routes/api/public/cron/post-drafts'
import { Route as ApiPublicGbpCallbackRouteImport } from './routes/api/public/gbp/callback'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersImportRoute =
  DashboardCustomersImportRouteImport.update({
    id: '/customers-import',
    path: '/customers-import',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostingLogRoute = DashboardPostingLogRouteImport.update({
  id: '/posting-log',
  path: '/posting-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRemovalsRoute = DashboardRemovalsRouteImport.update({
  id: '/removals',
  path: '/removals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStripeReadinessRoute =
  DashboardStripeReadinessRouteImport.update({
    id: '/stripe-readiness',
    path: '/stripe-readiness',
    getParentRoute: () => DashboardRoute,
  } as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostingAttemptsCsvRoute = ApiPostingAttemptsCsvRouteImport.update({
  id: '/api/posting-attempts/csv',
  path: '/api/posting-attempts/csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronOutreachTickRoute =
  ApiPublicCronOutreachTickRouteImport.update({
    id: '/api/public/cron/outreach-tick',
    path: '/api/public/cron/outreach-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPollYelpRoute = ApiPublicCronPollYelpRouteImport.update({
  id: '/api/public/cron/poll-yelp',
  path: '/api/public/cron/poll-yelp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPostDraftsRoute = ApiPublicCronPostDraftsRouteImport.update({
  id: '/api/public/cron/post-drafts',
  path: '/api/public/cron/post-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGbpCallbackRoute = ApiPublicGbpCallbackRouteImport.update({
  id: '/api/public/gbp/callback',
  path: '/api/public/gbp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/customers-import': typeof DashboardCustomersImportRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/posting-log': typeof DashboardPostingLogRoute
  '/dashboard/removals': typeof DashboardRemovalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stripe-readiness': typeof DashboardStripeReadinessRoute
  '/r/$token': typeof RTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/posting-attempts/csv': typeof ApiPostingAttemptsCsvRoute
  '/api/public/cron/outreach-tick': typeof ApiPublicCronOutreachTickRoute
  '/api/public/cron/poll-yelp': typeof ApiPublicCronPollYelpRoute
  '/api/public/cron/post-drafts': typeof ApiPublicCronPostDraftsRoute
  '/api/public/gbp/callback': typeof ApiPublicGbpCallbackRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/customers-import': typeof DashboardCustomersImportRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/posting-log': typeof DashboardPostingLogRoute
  '/dashboard/removals': typeof DashboardRemovalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stripe-readiness': typeof DashboardStripeReadinessRoute
  '/r/$token': typeof RTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/posting-attempts/csv': typeof ApiPostingAttemptsCsvRoute
  '/api/public/cron/outreach-tick': typeof ApiPublicCronOutreachTickRoute
  '/api/public/cron/poll-yelp': typeof ApiPublicCronPollYelpRoute
  '/api/public/cron/post-drafts': typeof ApiPublicCronPostDraftsRoute
  '/api/public/gbp/callback': typeof ApiPublicGbpCallbackRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/customers-import': typeof DashboardCustomersImportRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/posting-log': typeof DashboardPostingLogRoute
  '/dashboard/removals': typeof DashboardRemovalsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stripe-readiness': typeof DashboardStripeReadinessRoute
  '/r/$token': typeof RTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/posting-attempts/csv': typeof ApiPostingAttemptsCsvRoute
  '/api/public/cron/outreach-tick': typeof ApiPublicCronOutreachTickRoute
  '/api/public/cron/poll-yelp': typeof ApiPublicCronPollYelpRoute
  '/api/public/cron/post-drafts': typeof ApiPublicCronPostDraftsRoute
  '/api/public/gbp/callback': typeof ApiPublicGbpCallbackRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/approvals'
    | '/dashboard/connections'
    | '/dashboard/customers-import'
    | '/dashboard/inbox'
    | '/dashboard/posting-log'
    | '/dashboard/removals'
    | '/dashboard/settings'
    | '/dashboard/stripe-readiness'
    | '/r/$token'
    | '/dashboard/'
    | '/api/posting-attempts/csv'
    | '/api/public/cron/outreach-tick'
    | '/api/public/cron/poll-yelp'
    | '/api/public/cron/post-drafts'
    | '/api/public/gbp/callback'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/approvals'
    | '/dashboard/connections'
    | '/dashboard/customers-import'
    | '/dashboard/inbox'
    | '/dashboard/posting-log'
    | '/dashboard/removals'
    | '/dashboard/settings'
    | '/dashboard/stripe-readiness'
    | '/r/$token'
    | '/dashboard'
    | '/api/posting-attempts/csv'
    | '/api/public/cron/outreach-tick'
    | '/api/public/cron/poll-yelp'
    | '/api/public/cron/post-drafts'
    | '/api/public/gbp/callback'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/approvals'
    | '/dashboard/connections'
    | '/dashboard/customers-import'
    | '/dashboard/inbox'
    | '/dashboard/posting-log'
    | '/dashboard/removals'
    | '/dashboard/settings'
    | '/dashboard/stripe-readiness'
    | '/r/$token'
    | '/dashboard/'
    | '/api/posting-attempts/csv'
    | '/api/public/cron/outreach-tick'
    | '/api/public/cron/poll-yelp'
    | '/api/public/cron/post-drafts'
    | '/api/public/gbp/callback'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RTokenRoute: typeof RTokenRoute
  ApiPostingAttemptsCsvRoute: typeof ApiPostingAttemptsCsvRoute
  ApiPublicCronOutreachTickRoute: typeof ApiPublicCronOutreachTickRoute
  ApiPublicCronPollYelpRoute: typeof ApiPublicCronPollYelpRoute
  ApiPublicCronPostDraftsRoute: typeof ApiPublicCronPostDraftsRoute
  ApiPublicGbpCallbackRoute: typeof ApiPublicGbpCallbackRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connections': {
      id: '/dashboard/connections'
      path: '/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers-import': {
      id: '/dashboard/customers-import'
      path: '/customers-import'
      fullPath: '/dashboard/customers-import'
      preLoaderRoute: typeof DashboardCustomersImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posting-log': {
      id: '/dashboard/posting-log'
      path: '/posting-log'
      fullPath: '/dashboard/posting-log'
      preLoaderRoute: typeof DashboardPostingLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/removals': {
      id: '/dashboard/removals'
      path: '/removals'
      fullPath: '/dashboard/removals'
      preLoaderRoute: typeof DashboardRemovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stripe-readiness': {
      id: '/dashboard/stripe-readiness'
      path: '/stripe-readiness'
      fullPath: '/dashboard/stripe-readiness'
      preLoaderRoute: typeof DashboardStripeReadinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posting-attempts/csv': {
      id: '/api/posting-attempts/csv'
      path: '/api/posting-attempts/csv'
      fullPath: '/api/posting-attempts/csv'
      preLoaderRoute: typeof ApiPostingAttemptsCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/outreach-tick': {
      id: '/api/public/cron/outreach-tick'
      path: '/api/public/cron/outreach-tick'
      fullPath: '/api/public/cron/outreach-tick'
      preLoaderRoute: typeof ApiPublicCronOutreachTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/poll-yelp': {
      id: '/api/public/cron/poll-yelp'
      path: '/api/public/cron/poll-yelp'
      fullPath: '/api/public/cron/poll-yelp'
      preLoaderRoute: typeof ApiPublicCronPollYelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/post-drafts': {
      id: '/api/public/cron/post-drafts'
      path: '/api/public/cron/post-drafts'
      fullPath: '/api/public/cron/post-drafts'
      preLoaderRoute: typeof ApiPublicCronPostDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gbp/callback': {
      id: '/api/public/gbp/callback'
      path: '/api/public/gbp/callback'
      fullPath: '/api/public/gbp/callback'
      preLoaderRoute: typeof ApiPublicGbpCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardCustomersImportRoute: typeof DashboardCustomersImportRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardPostingLogRoute: typeof DashboardPostingLogRoute
  DashboardRemovalsRoute: typeof DashboardRemovalsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStripeReadinessRoute: typeof DashboardStripeReadinessRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardCustomersImportRoute: DashboardCustomersImportRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardPostingLogRoute: DashboardPostingLogRoute,
  DashboardRemovalsRoute: DashboardRemovalsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStripeReadinessRoute: DashboardStripeReadinessRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RTokenRoute: RTokenRoute,
  ApiPostingAttemptsCsvRoute: ApiPostingAttemptsCsvRoute,
  ApiPublicCronOutreachTickRoute: ApiPublicCronOutreachTickRoute,
  ApiPublicCronPollYelpRoute: ApiPublicCronPollYelpRoute,
  ApiPublicCronPostDraftsRoute: ApiPublicCronPostDraftsRoute,
  ApiPublicGbpCallbackRoute: ApiPublicGbpCallbackRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
